#开发环境 配置文件


#url: jdbc:mysql://localhost:3306/boot?serverTimezone=UTC
#  username: root
#  password: 123
#  driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



#mybatis:
#  mapper-locations: classpath:generator/*.xml

logging:
  level:
    com.cn.studyspringboot: debug
server:
  port: 8888






