#测试环境配置文件



spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:generator/*.xml

logging:
  level:
    com.zimug.bootlaunch: debug